name: Backend Quality Assurance Workflow
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  publish:
    name: Testing
    runs-on: ubuntu-latest
    container: node:20.11.1-alpine3.19
    services:
      db:
        image: postgres:16.2-alpine3.19
        env:
          POSTGRES_DB: test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Enter backend directory
        run: cd ./backend

      - name: Install node packages
        run: pnpm install

      - name: Inject Prisma types
        run: pnpm exec prisma generate

      - name: Run Prisma migrations
        run: pnpm exec prisma migrate deploy

      - name: Test application
        run: pnpm run test:ci

    env:
      DATABASE_URL: postgresql://admin:admin@db:5432/test?schema=public
      PRISMA_HIDE_UPDATE_MESSAGE: true
      FASTIFY_LOGGER: false
      PORT: 3000
